const os = require("os");
const { createCanvas } = require("canvas");
const fs = require("fs");
const path = require("path");

module.exports = {
  config: {
    name: "monitor",
    version: "3.0.0",
    author: "OPUSENSEI",
    countDown: 10,
    role: 2,
    shortDescription: "Animora Pro Monitor",
    category: "system"
  },

  onStart: async function ({ message }) {
    try {
      // ===== SYSTEM INFO =====
      const uptime = process.uptime();
      const h = Math.floor(uptime / 3600);
      const m = Math.floor((uptime % 3600) / 60);
      const s = Math.floor(uptime % 60);

      const totalMem = (os.totalmem() / 1024 / 1024).toFixed(0);
      const freeMem = (os.freemem() / 1024 / 1024).toFixed(0);
      const usedMem = totalMem - freeMem;

      const heap = (process.memoryUsage().heapUsed / 1024 / 1024).toFixed(0);

      const cpu = os.cpus().length;
      const platform = os.platform();
      const arch = os.arch();

      // ===== CANVAS =====
      const canvas = createCanvas(1000, 550);
      const ctx = canvas.getContext("2d");

      // Background
      ctx.fillStyle = "#0b0f14";
      ctx.fillRect(0, 0, 1000, 550);

      // Glow line
      ctx.strokeStyle = "#00ffcc";
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(40, 80);
      ctx.lineTo(960, 80);
      ctx.stroke();

      // Title
      ctx.fillStyle = "#00ffcc";
      ctx.font = "bold 36px Arial";
      ctx.fillText("Animora AI • System Monitor", 40, 60);

      // Box function
      function box(x, y, w, h, title, value) {
        ctx.fillStyle = "#11161c";
        ctx.fillRect(x, y, w, h);

        ctx.strokeStyle = "#1f2a35";
        ctx.strokeRect(x, y, w, h);

        ctx.fillStyle = "#4cc9f0";
        ctx.font = "20px Arial";
        ctx.fillText(title, x + 15, y + 30);

        ctx.fillStyle = "#ffffff";
        ctx.font = "18px Arial";
        ctx.fillText(value, x + 15, y + 70);
      }

      // ===== BOXES =====
      box(40, 100, 280, 120, "⏱ Uptime", `${h}h ${m}m ${s}s`);
      box(360, 100, 280, 120, "📊 RAM", `${usedMem}/${totalMem} MB`);
      box(680, 100, 280, 120, "🔥 CPU", `${cpu} Cores`);

      box(40, 260, 280, 120, "💾 Heap", `${heap} MB`);
      box(360, 260, 280, 120, "💻 Platform", platform);
      box(680, 260, 280, 120, "⚙️ Arch", arch);

      // Status
      ctx.fillStyle = "#00ff88";
      ctx.font = "bold 22px Arial";
      ctx.fillText("● System Status: Running Smoothly", 40, 450);

      // Footer
      ctx.fillStyle = "#6c757d";
      ctx.font = "16px Arial";
      ctx.fillText("Generated by Animora AI Monitor", 40, 500);

      // ===== SAVE =====
      const filePath = path.join(__dirname, "animora_monitor.png");
      fs.writeFileSync(filePath, canvas.toBuffer());

      // ===== SEND =====
      return message.reply({
        body: "📊 Animora System Dashboard",
        attachment: fs.createReadStream(filePath)
      });

    } catch (err) {
      return message.reply("❌ Error: " + err.message);
    }
  }
};
